<?php

use Illuminate\Database\Seeder;
use App\LedgerAccount;

class ChartOfAccountsSeeder extends Seeder
{
    /**
     * Seed the Chart of Accounts for Zimbabwean Schools
     *
     * @return void
     */
    public function run()
    {
        $accounts = [
            // ASSETS (1000-1999)
            [
                'account_code' => '1000',
                'account_name' => 'Cash on Hand',
                'account_type' => 'asset',
                'category' => 'Current Assets',
                'description' => 'Physical cash held by the school',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1010',
                'account_name' => 'Bank Account - USD',
                'account_type' => 'asset',
                'category' => 'Current Assets',
                'description' => 'Main USD bank account',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1011',
                'account_name' => 'Bank Account - ZWL',
                'account_type' => 'asset',
                'category' => 'Current Assets',
                'description' => 'ZWL/ZIG bank account',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1100',
                'account_name' => 'Accounts Receivable - Students',
                'account_type' => 'asset',
                'category' => 'Current Assets',
                'description' => 'Outstanding student fees',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1200',
                'account_name' => 'Inventory - School Supplies',
                'account_type' => 'asset',
                'category' => 'Current Assets',
                'description' => 'School supplies and materials',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1210',
                'account_name' => 'Inventory - Grocery Stock',
                'account_type' => 'asset',
                'category' => 'Current Assets',
                'description' => 'Grocery items for students',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1500',
                'account_name' => 'Property, Plant & Equipment',
                'account_type' => 'asset',
                'category' => 'Fixed Assets',
                'description' => 'School buildings, land, and equipment',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1510',
                'account_name' => 'Furniture & Fixtures',
                'account_type' => 'asset',
                'category' => 'Fixed Assets',
                'description' => 'School furniture and fixtures',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1520',
                'account_name' => 'Computer Equipment',
                'account_type' => 'asset',
                'category' => 'Fixed Assets',
                'description' => 'Computers and IT equipment',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1530',
                'account_name' => 'Vehicles',
                'account_type' => 'asset',
                'category' => 'Fixed Assets',
                'description' => 'School vehicles and transport',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1600',
                'account_name' => 'Accumulated Depreciation - PPE',
                'account_type' => 'asset',
                'category' => 'Fixed Assets',
                'description' => 'Accumulated depreciation on property, plant & equipment',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1610',
                'account_name' => 'Accumulated Depreciation - Furniture',
                'account_type' => 'asset',
                'category' => 'Fixed Assets',
                'description' => 'Accumulated depreciation on furniture',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1620',
                'account_name' => 'Accumulated Depreciation - Computers',
                'account_type' => 'asset',
                'category' => 'Fixed Assets',
                'description' => 'Accumulated depreciation on computers',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '1630',
                'account_name' => 'Accumulated Depreciation - Vehicles',
                'account_type' => 'asset',
                'category' => 'Fixed Assets',
                'description' => 'Accumulated depreciation on vehicles',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],

            // LIABILITIES (2000-2999)
            [
                'account_code' => '2000',
                'account_name' => 'Accounts Payable - Suppliers',
                'account_type' => 'liability',
                'category' => 'Current Liabilities',
                'description' => 'Amounts owed to suppliers',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '2100',
                'account_name' => 'Salaries Payable',
                'account_type' => 'liability',
                'category' => 'Current Liabilities',
                'description' => 'Unpaid staff salaries',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '2200',
                'account_name' => 'PAYE Payable',
                'account_type' => 'liability',
                'category' => 'Current Liabilities',
                'description' => 'Pay As You Earn tax payable to ZIMRA',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '2210',
                'account_name' => 'NSSA Payable',
                'account_type' => 'liability',
                'category' => 'Current Liabilities',
                'description' => 'National Social Security Authority contributions payable',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '2220',
                'account_name' => 'NEC Payable',
                'account_type' => 'liability',
                'category' => 'Current Liabilities',
                'description' => 'National Employment Council levy payable',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '2300',
                'account_name' => 'Student Deposits',
                'account_type' => 'liability',
                'category' => 'Current Liabilities',
                'description' => 'Refundable student deposits',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],

            // EQUITY (3000-3999)
            [
                'account_code' => '3000',
                'account_name' => 'Retained Earnings',
                'account_type' => 'equity',
                'category' => 'Equity',
                'description' => 'Accumulated profits/losses',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '3100',
                'account_name' => 'Current Year Earnings',
                'account_type' => 'equity',
                'category' => 'Equity',
                'description' => 'Current year profit/loss',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],

            // INCOME (4000-4999)
            [
                'account_code' => '4000',
                'account_name' => 'Tuition Fees - Day Students',
                'account_type' => 'income',
                'category' => 'Revenue',
                'description' => 'Day student tuition fees',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '4010',
                'account_name' => 'Tuition Fees - Boarding Students',
                'account_type' => 'income',
                'category' => 'Revenue',
                'description' => 'Boarding student tuition fees',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '4020',
                'account_name' => 'Registration Fees',
                'account_type' => 'income',
                'category' => 'Revenue',
                'description' => 'Student registration fees',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '4030',
                'account_name' => 'Exam Fees',
                'account_type' => 'income',
                'category' => 'Revenue',
                'description' => 'Examination fees',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '4040',
                'account_name' => 'Boarding Fees',
                'account_type' => 'income',
                'category' => 'Revenue',
                'description' => 'Boarding accommodation fees',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '4050',
                'account_name' => 'Uniform Sales',
                'account_type' => 'income',
                'category' => 'Revenue',
                'description' => 'School uniform sales',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '4060',
                'account_name' => 'Grocery Sales',
                'account_type' => 'income',
                'category' => 'Revenue',
                'description' => 'Student grocery sales',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '4100',
                'account_name' => 'Donations',
                'account_type' => 'income',
                'category' => 'Other Income',
                'description' => 'Donations and grants received',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '4110',
                'account_name' => 'Government Grants',
                'account_type' => 'income',
                'category' => 'Other Income',
                'description' => 'Government funding and grants',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '4200',
                'account_name' => 'Interest Income',
                'account_type' => 'income',
                'category' => 'Other Income',
                'description' => 'Interest earned on bank accounts',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '4300',
                'account_name' => 'Foreign Exchange Gain',
                'account_type' => 'income',
                'category' => 'Other Income',
                'description' => 'Gains from foreign exchange transactions',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],

            // EXPENSES (5000-5999)
            [
                'account_code' => '5000',
                'account_name' => 'Salaries & Wages - Teaching Staff',
                'account_type' => 'expense',
                'category' => 'Personnel Costs',
                'description' => 'Teaching staff salaries',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5010',
                'account_name' => 'Salaries & Wages - Support Staff',
                'account_type' => 'expense',
                'category' => 'Personnel Costs',
                'description' => 'Support staff salaries',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5020',
                'account_name' => 'PAYE Expense',
                'account_type' => 'expense',
                'category' => 'Personnel Costs',
                'description' => 'Pay As You Earn tax expense',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5030',
                'account_name' => 'NSSA Expense',
                'account_type' => 'expense',
                'category' => 'Personnel Costs',
                'description' => 'NSSA contributions',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5040',
                'account_name' => 'NEC Levy',
                'account_type' => 'expense',
                'category' => 'Personnel Costs',
                'description' => 'National Employment Council levy',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5100',
                'account_name' => 'Electricity Expense',
                'account_type' => 'expense',
                'category' => 'Utilities',
                'description' => 'Electricity bills',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5110',
                'account_name' => 'Water Expense',
                'account_type' => 'expense',
                'category' => 'Utilities',
                'description' => 'Water bills',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5120',
                'account_name' => 'Internet & Communication',
                'account_type' => 'expense',
                'category' => 'Utilities',
                'description' => 'Internet and phone expenses',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5200',
                'account_name' => 'Building Maintenance',
                'account_type' => 'expense',
                'category' => 'Maintenance',
                'description' => 'Building repairs and maintenance',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5210',
                'account_name' => 'Equipment Maintenance',
                'account_type' => 'expense',
                'category' => 'Maintenance',
                'description' => 'Equipment repairs and maintenance',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5300',
                'account_name' => 'Depreciation Expense - PPE',
                'account_type' => 'expense',
                'category' => 'Depreciation',
                'description' => 'Depreciation on property, plant & equipment',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5310',
                'account_name' => 'Depreciation Expense - Furniture',
                'account_type' => 'expense',
                'category' => 'Depreciation',
                'description' => 'Depreciation on furniture',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5320',
                'account_name' => 'Depreciation Expense - Computers',
                'account_type' => 'expense',
                'category' => 'Depreciation',
                'description' => 'Depreciation on computers',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5330',
                'account_name' => 'Depreciation Expense - Vehicles',
                'account_type' => 'expense',
                'category' => 'Depreciation',
                'description' => 'Depreciation on vehicles',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5400',
                'account_name' => 'Teaching Materials',
                'account_type' => 'expense',
                'category' => 'Academic Expenses',
                'description' => 'Books, stationery, and teaching aids',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5410',
                'account_name' => 'Laboratory Supplies',
                'account_type' => 'expense',
                'category' => 'Academic Expenses',
                'description' => 'Science lab supplies and chemicals',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5420',
                'account_name' => 'Sports Equipment',
                'account_type' => 'expense',
                'category' => 'Academic Expenses',
                'description' => 'Sports and physical education equipment',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5500',
                'account_name' => 'Office Supplies',
                'account_type' => 'expense',
                'category' => 'Administration',
                'description' => 'Office stationery and supplies',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5510',
                'account_name' => 'Printing & Photocopying',
                'account_type' => 'expense',
                'category' => 'Administration',
                'description' => 'Printing and copying expenses',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5520',
                'account_name' => 'Bank Charges',
                'account_type' => 'expense',
                'category' => 'Administration',
                'description' => 'Bank fees and charges',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5530',
                'account_name' => 'Professional Fees',
                'account_type' => 'expense',
                'category' => 'Administration',
                'description' => 'Legal, accounting, and consulting fees',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5600',
                'account_name' => 'Transport & Fuel',
                'account_type' => 'expense',
                'category' => 'Transport',
                'description' => 'Vehicle fuel and transport costs',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5610',
                'account_name' => 'Vehicle Insurance',
                'account_type' => 'expense',
                'category' => 'Transport',
                'description' => 'Vehicle insurance premiums',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5700',
                'account_name' => 'Food & Catering',
                'account_type' => 'expense',
                'category' => 'Boarding Expenses',
                'description' => 'Food and catering for boarding students',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5710',
                'account_name' => 'Cleaning Supplies',
                'account_type' => 'expense',
                'category' => 'Boarding Expenses',
                'description' => 'Cleaning materials and supplies',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5800',
                'account_name' => 'Foreign Exchange Loss',
                'account_type' => 'expense',
                'category' => 'Other Expenses',
                'description' => 'Losses from foreign exchange transactions',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
            [
                'account_code' => '5900',
                'account_name' => 'Miscellaneous Expenses',
                'account_type' => 'expense',
                'category' => 'Other Expenses',
                'description' => 'Other miscellaneous expenses',
                'opening_balance' => 0,
                'current_balance' => 0,
                'is_active' => true,
            ],
        ];

        foreach ($accounts as $account) {
            LedgerAccount::updateOrCreate(
                ['account_code' => $account['account_code']],
                $account
            );
        }

        $this->command->info('Chart of Accounts seeded successfully!');
        $this->command->info('Total accounts created: ' . count($accounts));
    }
}
